name: Build and Deploy

on:
  pull_request:
    branches:
      - master
    types: [ closed ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/dep-install

      - name: Run test
        run: pnpm test

      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
        id: pkg_version

      - name: Get changed for package.json
        id: pkg-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            package.json

      - name: Publish package to NPM
        if: steps.pkg-changed.outputs.any_changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Publish image to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fe-dev-server:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/fe-dev-server:${{ steps.pkg_version.outputs.tag }}
