name: Run Test

on:
  pull_request:
    branches:
      - 'feature/*'
      - 'refactor/*'
      - 'bugfix/*'
      - 'release/*'
      - 'master'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/dep-install

      - name: Run test
        run: pnpm test
